=== maxxgor79/emul2/other/src/resources/schema/JSpeccy.xsd
<?xml version="1.0" encoding="ISO-8859-1"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://xml.netbeans.org/schema/JSpeccy"
    xmlns:tns="http://xml.netbeans.org/schema/JSpeccy"
    elementFormDefault="qualified">
    <xsd:element name="JSpeccySettings" type="tns:JSpeccySettingsType"/>
    <xsd:complexType name="SpectrumType">
        <xsd:sequence>
            <xsd:element name="Issue2" default="false" type="xsd:boolean"/>
            <xsd:element name="AYEnabled48k" type="xsd:boolean" default="false"/>
            <xsd:element name="mutedSound" type="xsd:boolean" default="false"/>
            <xsd:element name="loadingNoise" type="xsd:boolean" default="true"/>
            <xsd:element name="ULAplus" type="xsd:boolean" default="false"/>
            <xsd:element name="defaultModel" default="1" form="qualified">
                <xsd:simpleType>
                    <xsd:restriction base="xsd:integer">
                        <xsd:maxInclusive value="5"/>
                        <xsd:minInclusive value="0"/>
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:element>
            <xsd:element name="framesInt" form="qualified" default="2">
                <xsd:simpleType>
                    <xsd:restriction base="xsd:integer">
                        <xsd:maxInclusive value="10"/>
                        <xsd:minInclusive value="2"/>
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:element>
            <xsd:element name="doubleSize" type="xsd:boolean" default="false"/>
            <xsd:element name="multifaceEnabled" type="xsd:boolean" default="false"/>
            <xsd:element name="mf128on48K" default="false" type="xsd:boolean"/>
            <xsd:element name="hifiSound" type="xsd:boolean" default="false"/>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="MemoryType">
        <xsd:sequence>
            <xsd:element name="RomsDirectory" type="xsd:string"/>
            <xsd:element name="Rom48k" type="xsd:string" default="spectrum.rom"/>
            <xsd:element name="Rom128k0" type="xsd:string" default="128-0.rom"/>
            <xsd:element name="Rom128k1" type="xsd:string" default="128-1.rom"/>
            <xsd:element name="RomPlus20" type="xsd:string" default="plus2-0.rom"/>
            <xsd:element name="RomPlus21" type="xsd:string" default="plus2-1.rom"/>
            <xsd:element name="RomPlus30" type="xsd:string" default="plus3-0.rom"/>
            <xsd:element name="RomPlus31" type="xsd:string" default="plus3-1.rom"/>
            <xsd:element name="RomPlus32" type="xsd:string" default="plus3-2.rom"/>
            <xsd:element name="RomPlus33" type="xsd:string" default="plus3-3.rom"/>
            <xsd:element name="RomMF1" type="xsd:string" default="mf1.rom"/>
            <xsd:element name="RomMF128" type="xsd:string" default="mf128.rom"/>
            <xsd:element name="RomMFPlus3" type="xsd:string" default="mfplus3.rom"/>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="TapeType">
        <xsd:sequence>
            <xsd:element name="flashload" type="xsd:boolean" default="true"/>
            <xsd:element name="accelerateLoading" type="xsd:boolean" default="true"/>
            <xsd:element name="enableSaveTraps" type="xsd:boolean" default="true"/>
            <xsd:element name="highSamplingFreq" type="xsd:boolean" default="false"/>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="KeyboardJoystickType">
        <xsd:sequence>
            <xsd:element name="JoystickModel" default="0">
                <xsd:simpleType>
                    <xsd:restriction base="xsd:integer">
                        <xsd:maxInclusive value="5"/>
                        <xsd:minInclusive value="0"/>
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:element>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="AY8912Type">
        <xsd:sequence>
            <xsd:element name="soundMode" default="0">
                <xsd:simpleType>
                    <xsd:restriction base="xsd:integer">
                        <xsd:maxInclusive value="3"/>
                        <xsd:minInclusive value="0"/>
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:element>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="JSpeccySettingsType">
        <xsd:sequence>
            <xsd:element name="SpectrumSettings" type="tns:SpectrumType"/>
            <xsd:element name="MemorySettings" type="tns:MemoryType"/>
            <xsd:element name="TapeSettings" type="tns:TapeType"/>
            <xsd:element name="KeyboardJoystickSettings" type="tns:KeyboardJoystickType"/>
            <xsd:element name="AY8912Settings" type="tns:AY8912Type"/>
            <xsd:element name="RecentFilesSettings" type="tns:RecentFilesType"/>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="RecentFilesType">
        <xsd:sequence>
            <xsd:element name="recentFile0" type="xsd:string"/>
            <xsd:element name="recentFile1" type="xsd:string"/>
            <xsd:element name="recentFile2" type="xsd:string"/>
            <xsd:element name="recentFile3" type="xsd:string"/>
            <xsd:element name="recentFile4" type="xsd:string"/>
            <xsd:element name="lastSnapshotDir" type="xsd:string"/>
            <xsd:element name="lastTapeDir" type="xsd:string"/>
        </xsd:sequence>
    </xsd:complexType>
</xsd:schema>

=== maxxgor79/emul2/other/src/resources/schema/JSpeccy.xml
<?xml version="1.0" encoding="ISO-8859-1"?>

<!--
    Document   : JSpeccy.xml
    Created on : 23 de diciembre de 2010, 11:16
    Author     : jsanchez
    Description:
        Purpose of the document follows.
-->

<ns0:JSpeccySettings  xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
   xmlns:ns0='http://xml.netbeans.org/schema/JSpeccy'
   xsi:schemaLocation='http://xml.netbeans.org/schema/JSpeccy JSpeccy.xsd'>
    <ns0:SpectrumSettings>
        <ns0:Issue2>false</ns0:Issue2>
        <ns0:AYEnabled48k>false</ns0:AYEnabled48k>
        <ns0:mutedSound>false</ns0:mutedSound>
        <ns0:loadingNoise>true</ns0:loadingNoise>
        <ns0:ULAplus>false</ns0:ULAplus>
        <ns0:defaultModel>1</ns0:defaultModel>
        <ns0:framesInt>2</ns0:framesInt>
        <ns0:doubleSize>false</ns0:doubleSize>
        <ns0:multifaceEnabled>false</ns0:multifaceEnabled>
        <ns0:mf128on48K>false</ns0:mf128on48K>
        <ns0:hifiSound>false</ns0:hifiSound>
    </ns0:SpectrumSettings>
    <ns0:MemorySettings>
        <ns0:RomsDirectory></ns0:RomsDirectory>
        <ns0:Rom48k>spectrum.rom</ns0:Rom48k>
        <ns0:Rom128k0>128-0.rom</ns0:Rom128k0>
        <ns0:Rom128k1>128-1.rom</ns0:Rom128k1>
        <ns0:RomPlus20>plus2-0.rom</ns0:RomPlus20>
        <ns0:RomPlus21>plus2-1.rom</ns0:RomPlus21>
        <ns0:RomPlus30>plus3-0.rom</ns0:RomPlus30>
        <ns0:RomPlus31>plus3-1.rom</ns0:RomPlus31>
        <ns0:RomPlus32>plus3-2.rom</ns0:RomPlus32>
        <ns0:RomPlus33>plus3-3.rom</ns0:RomPlus33>
        <ns0:RomMF1>mf1.rom</ns0:RomMF1>
        <ns0:RomMF128>mf128.rom</ns0:RomMF128>
        <ns0:RomMFPlus3>mfplus3.rom</ns0:RomMFPlus3>
    </ns0:MemorySettings>
    <ns0:TapeSettings>
        <ns0:flashload>true</ns0:flashload>
        <ns0:accelerateLoading>true</ns0:accelerateLoading>
        <ns0:enableSaveTraps>true</ns0:enableSaveTraps>
        <ns0:highSamplingFreq>false</ns0:highSamplingFreq>
    </ns0:TapeSettings>
    <ns0:KeyboardJoystickSettings>
        <ns0:JoystickModel>0</ns0:JoystickModel>
    </ns0:KeyboardJoystickSettings>
    <ns0:AY8912Settings>
        <ns0:soundMode>0</ns0:soundMode>
    </ns0:AY8912Settings>
    <ns0:RecentFilesSettings>
        <ns0:recentFile0></ns0:recentFile0>
        <ns0:recentFile1></ns0:recentFile1>
        <ns0:recentFile2></ns0:recentFile2>
        <ns0:recentFile3></ns0:recentFile3>
        <ns0:recentFile4></ns0:recentFile4>
        <ns0:lastSnapshotDir></ns0:lastSnapshotDir>
        <ns0:lastTapeDir></ns0:lastTapeDir>
    </ns0:RecentFilesSettings>

</ns0:JSpeccySettings>
